iopipe/iopipe-java

src/main/java/com/iopipe/IOpipeService.java
src/main/java/com/iopipe/__TimeOutWatchDog__.java
src/test/resources/log4j2-test.xml

This fixes issue #13 by not having logging messages duplicated.
Additionally, some debug logs which should have been errors have been changed (when a request fails and when the watchdog thread times out).

Pull Request for Issue #13

---

README.md
example/pom.xml
src/main/java/com/iopipe/IOpipeConstants.java

This will  update constants and across repo, going to do a 0.4 release and then the UI will show the agent version correctly :)

Update version across repo to 0.4

---

README.md

Move some things around, so that build instructions are at the top. Also helps address #1. @XerTheSquirrel looking for feedback, if we need to add any more dependency instructions re:feedback in Slack the other day.

Docs reorganization and edits

---

README.md

@XerTheSquirrel I'm unsure of what the API should look like for the "using service directly" example

Update README per new API

---

.gitignore
circle.yml
example/pom.xml
example/serverless.yml

Deploy example functions for monitoring/QA purposes
This closes #12

Add Serverless config to deploy funcs

---

README.md

Closes #24, moves badges and adds a build status badge

Move badges, add Circle badge

---

example/serverless.yml

Add profiler func config to example serverless.yml

---

src/main/java/com/iopipe/IOpipeExecution.java
src/main/java/com/iopipe/IOpipeService.java
src/main/java/com/iopipe/SystemMeasurement.java
src/test/java/com/iopipe/Engine.java
src/test/java/com/iopipe/__DoDiskReportCheck__.java

This contains a refactor of `SystemMeasurement` since it was really ugly and it was just a mess and it also contains reporting disk usage of the `/tmp` directory.
The refactor should help in the future if more things about the system want to be queried in the future.

Report Disk Usage and refactor `SystemMeasurement`

---

README.md

This refers to the Gradle build file, note that this will 404 until the PR in the examples is merged. So this is waiting on: https://github.com/iopipe/examples/pull/15 first.

Refer to Gradle in the README.

---

.gitignore
PROFILER.md
src/main/java/com/iopipe/plugin/profiler/BufferPoolStatistics.java
src/main/java/com/iopipe/plugin/profiler/ClassLoaderStatistics.java
src/main/java/com/iopipe/plugin/profiler/CompilerStatistics.java
src/main/java/com/iopipe/plugin/profiler/GarbageCollectorStatistics.java
src/main/java/com/iopipe/plugin/profiler/ManagementStatistics.java
src/main/java/com/iopipe/plugin/profiler/MemoryPoolStatistics.java
src/main/java/com/iopipe/plugin/profiler/MemoryStatistics.java
src/main/java/com/iopipe/plugin/profiler/MemoryUsageStatistic.java
src/main/java/com/iopipe/plugin/profiler/MemoryUsageStatistics.java
src/main/java/com/iopipe/plugin/profiler/ProfilerExecution.java
src/main/java/com/iopipe/plugin/profiler/ProfilerPlugin.java
src/main/java/com/iopipe/plugin/profiler/ThreadStatistics.java
src/main/java/com/iopipe/plugin/profiler/TrackedThread.java
src/main/java/com/iopipe/plugin/profiler/TrackedThreadNodeTraversal.java
src/main/java/com/iopipe/plugin/profiler/Tracker.java
src/main/java/com/iopipe/plugin/profiler/UptimeStatistics.java
src/main/java/com/iopipe/plugin/profiler/__CPUExport__.java
src/main/java/com/iopipe/plugin/profiler/__StatExport__.java

The goal of this PR will be to add some extra statistics about the JVM and include them in the profiler report as extra keys, this information would be seen on the snapshot properties page in VisualVM.

Profiler Statistics Update

---

.circleci/performrelease.sh

Fixes a syntax error in the release script.

Correct syntax error in release performing script. (Fixes #125)

---

README.md
pom.xml
src/main/java/com/iopipe/IOpipeConstants.java

The build system released and pushed commits under a tag and not the master branch, so this is merging that tag into master so it reflects the latest version.

Merge release commit onto master.

---

CODE_OF_CONDUCT.md

This adds a code of conduct to the repository.
This is for 1.6.0, merge after 1.5.0 release.

Add code of conduct. (Fixes #119)

---

README.md
pom.xml
src/main/java/com/iopipe/IOpipeConfiguration.java
src/main/java/com/iopipe/IOpipeExecution.java
src/main/java/com/iopipe/IOpipeService.java
src/main/java/com/iopipe/__Plugins__.java
src/main/java/com/iopipe/__TimeOutWatchDog__.java
src/main/java/com/iopipe/plugin/eventinfo/EventInfoDecoders.java
src/main/java/com/iopipe/plugin/profiler/ProfilerExecution.java
src/test/java/com/iopipe/Engine.java
src/test/java/com/iopipe/__DoEventInfoPlugin__.java
src/test/resources/tinylog.properties

This is replacing log4j2 with a lighter logging framework, which should decrease cold start times.

Use a lighter logging framework. (Fixes #80)

---

pom.xml
src/main/java/com/iopipe/plugin/eventinfo/EventInfoDecoders.java
src/main/java/com/iopipe/plugin/eventinfo/SQSDecoder.java
src/test/java/com/iopipe/Engine.java
src/test/java/com/iopipe/__DoEventInfoPlugin__.java
src/test/java/com/iopipe/__WrappedConnectionFactory__.java
src/test/resources/com/iopipe/eventinfo_sqs.json

This is initial work on support for SQS events.

Support SQS in Event-Info (Fixes #89)

---

.version-rules.xml
pom.xml

Updates the dependencies to the latest version.

Update POM dependencies (Fixes #133)

---

src/main/java/com/iopipe/IOpipeExecution.java
src/main/java/com/iopipe/__Shared__.java
src/test/java/com/iopipe/StandardPushEvent.java

Switches processId to using a random UUID rather than a PID.

Switch processId to using a UUID. (Fixes #151)

---

README.md
pom.xml
src/main/java/com/iopipe/IOpipeConstants.java

Corrects the repository for 1.8.0.

Correct repository for 1.8.0.

---

pom.xml

This updates the dependencies along with performing other changes to the POM to make it more build stable.

Update dependencies and the POM. (Fixes #150)

---

src/main/java/com/iopipe/generic/GenericAWSRequestHandler.java

Moves the hander code around to support event-info and still catching any exceptions thrown for failed object conversions.
Fixes #165.

Move handler code around to support event-info. (Fixes #165)

---

README.md
pom.xml
src/main/java/com/iopipe/IOpipeConstants.java

Correct master for 1.9.0.

---

src/main/java/com/iopipe/plugin/eventinfo/EventInfoDecoders.java

Gracefully handle class loading failures for event info.

---

src/main/java/com/iopipe/plugin/eventinfo/EventInfoDecoders.java

Slight refactor and optimization of the event-info handler.
Fixes #148.

Event-info minor refactor. Fixes #148

---

README.md
pom.xml
src/main/java/com/iopipe/IOpipeConstants.java

Merge the tag back in and correct for 1.10.0 development.

Merge tag back in for 1.10.0.

---

src/main/java/com/iopipe/IOpipeConfiguration.java
src/main/java/com/iopipe/IOpipeConfigurationBuilder.java
src/main/java/com/iopipe/IOpipeConstants.java
src/test/java/com/iopipe/MockEngine.java

Remove deprecated fields/methods that were changed for the signer.

Remove deprecated profiler methods/fields. (Fixes #180)

---

.circleci/config.yml

Updates the regex for CircleCI which should match tags.

Update regex for CircleCI

---

pom.xml

Going to try having a constant version number instead because I get unauthorized for BinTray, it might not be able to handle it properly.

Do not use a variable version number, make it constant.

---

pom.xml
src/main/java/com/iopipe/IOpipeConfiguration.java

This corrects a fatal crash related to missing configuration resource.

Correct fatal crash related to missing configuration resource.

---

src/main/java/com/iopipe/IOpipeConfiguration.java
src/main/java/com/iopipe/IOpipeService.java

This removes the static configuration.

Remove the static configuration variable. (Fixes #172)

---

pom.xml

Updates the POM version to 1.11.0, this will be needed for future manual deploy.

Update POM version to 1.11.0

---

src/main/java/com/iopipe/IOpipeConfiguration.java
src/main/java/com/iopipe/IOpipeService.java

This reverts the non-static configuration and makes it static again.

Undo PR #207: Non-Static Configuration

---

.circleci/release.sh

Remove check for NodeJS in the release script.

Remove check for NodeJS in the release script.

---

.circleci/release.sh

Do not change directories to run maven.

Do not change directories to run maven.

---

.circleci/release.sh

Correct syntax error in call to maven sync.

Correct syntax error in call to maven sync.

---

pom.xml

Bump version to 1.12.0.

---

README.md
src/main/java/com/iopipe/generic/EntryPoint.java

This adds `IOPIPE_HANDLER` for GEP to match Python.

Add extra environment variable for GEP.

---

.circleci/layers.sh

The layer publishing script had an error in it, just a missing slash.

Correct layer publishing script.

---

pom.xml

This updates the versions for all the various dependencies.

Update versions of dependencies.
