src/main/java/com/iopipe/IOpipeMeasurement.java
Per update to the [schema](https://github.com/iopipe/iopipe-js-core/blob/master/src/schema.json), change the java key to the more generalized runtime key. Apologies that my editor made a bunch of whitespace updates.
Q: Should we remove the COPY_PROPERTIES List? Seems possibly useful later on.
=> Add runtime key/information

example/serverless.yml
Updates schedule for erroring event (throws runtime error because no input found)
=> Update serverless scheduler for qa event

src/main/java/com/iopipe/IOpipeConstants.java, src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/IOpipeMeasurement.java, src/main/java/com/iopipe/IOpipeService.java, src/main/java/com/iopipe/__TimeOutWatchDog__.java, src/main/java/com/iopipe/plugin/IOpipePluginExecution.java, src/main/java/com/iopipe/plugin/profiler/ProfilerExecution.java
This is an update to the profiler so that it can report jwtAccess tokens.
This is currently in progress.
There is going to be an incompatible change which will be performed in the `IOpipeMeasurement` class and that will be the removal of `buildRequest()`. That method should not have been in that class and it should not have been public anyway, the class should just store some measurement information and such accordingly, not perform much more work on building requests. This should have no impact at all because there is really no need for the user to build requests when that is automatically done by the service.
=> Profiler update for jwtAccess Tokens

src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/SystemMeasurement.java
This uses bytes instead of KiB for the os.environment fields, specifically `totalmem`, `freemem`, and `usedmem`.
This fixes issue #56.
=> Report total, used, and free memory in bytes instead of KiB.

src/main/java/com/iopipe/IOpipeConstants.java, src/main/java/com/iopipe/IOpipeExecution.java, src/test/java/com/iopipe/Engine.java, src/test/java/com/iopipe/__DoLongValueCustomMetric__.java
Do not send very long custom metric values in the report and instead warn when they are sent.
Fixes #58
=> Emit warning when custom metric value is too long and do not send in the report. (Fixes #58)

src/main/java/com/iopipe/IOpipeConfiguration.java
This fixes the issue where underscores and hyphens are not comparable to each other, it now ignores case and considers both of those characters to be the same.
Fixes #61.
=> For plugin names, make hyphen and underscore comparable (Fixes #61).

src/main/java/com/iopipe/plugin/profiler/ProfilerPlugin.java, src/main/java/com/iopipe/plugin/trace/TracePlugin.java
This sets the version for the trace and profiler plugins to use 1.2.0 instead of matching the agent version.
=> Use version 1.2.0 for the profiler and trace plugin.

PROFILER.md, README.md, src/main/java/com/iopipe/IOpipeConfiguration.java
This matches the Python agent and uses `_ENABLED` for the suffix for environment variables that enable or disable plugins.
=> Change plugins being enabling environment variable to match the Python agent (_ENABLED), fixes #64.

src/main/java/com/iopipe/SystemMeasurement.java, src/main/java/com/iopipe/plugin/profiler/ThreadStatistics.java, src/main/java/com/iopipe/plugin/profiler/TrackedThread.java
This corrects the JavaDoc tags for 1.4.0.
=> Correct JavaDoc tags for 1.4.0

pom.xml
An extra `-SNAPSHOT` has appeared in the POM, this removes it since it is not valid.
=> Remove the extra -SNAPSHOT, fixes #93.

README.md
This uses a remote service which uses anything from the Maven central repository, so this saves us the hassle of generating documentation in our releases. Also means we do not need to setup a branch or such in GitHub.
It does need a badge however in the README, but that is not really an issue.
=> Use javadoc.io to host our JavaDocs (fixes #99).

README.md, src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/SimpleRequestHandlerWrapper.java, src/main/java/com/iopipe/SimpleRequestStreamHandlerWrapper.java, src/main/java/com/iopipe/package-info.java
This documents how to access the AWS `Context` object, this is a bit more explicit in the JavaDocs compared to before.
=> Document how to access the context and use better wording (Fixes #21).

src/main/java/com/iopipe/SystemMeasurement.java
This corrects the off-by-one in the CPU times.
=> Correct off-by-one in CPU time recording. (Fixes #113)

src/main/java/com/iopipe/plugin/profiler/ThreadStatistics.java
Fixes #96.
This should fix that `NullPointerException` in the threading statistics code. I ran it 75 times in a row and I have not hit the error, so I believe it to be fixed.
=> Fix NullPointerException in threading statistics code (Fixes #96)

src/test/java/com/iopipe/StandardPushEvent.java, src/test/java/com/iopipe/__DoDiskReportCheck__.java
This fixes #118 when the disk usage in `/tmp` is really low the check fails. This changes the test to use doubles and NaN.
=> Fix Disk Usage check failing when low disk space is used (Fixes #118)

src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/IOpipeService.java, src/main/java/com/iopipe/plugin/trace/TraceUtils.java, src/test/java/com/iopipe/Engine.java, src/test/java/com/iopipe/__DoTracePlugin__.java
This is a work in progress which adds a mean to obtain `IOpipeExecution` statically without needing to have it passed.
=> Add static means to obtain IOpipeExecution (Fixes #76)

src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/IOpipeService.java, src/main/java/com/iopipe/__Shared__.java, src/main/java/com/iopipe/__TimeOutWatchDog__.java, src/main/java/com/iopipe/plugin/eventinfo/EventInfoExecution.java, src/main/java/com/iopipe/plugin/profiler/ProfilerExecution.java
This change was simple as it does not spawn a new thread.
All `Thread`s have to have a `ThreadGroup` so the profiler requires no changes, although it will only profile the name.
The profiler still works, but I am thinking of putting the IOpipe service threads in their own thread group so the profiler does not pick them up for profiling.
=> Do not spawn a new thread when invoking an execution (Fixes #84)

src/main/java/com/iopipe/IOpipeConfiguration.java
This fixes a fatal crash for when `IOPIPE_ENABLED` is specified in the environment.
Also as a future security against this problem, I have opted to disable IOpipe if the default configuration cannot be built for some reason. So for example it will say this instead of crashing and doing nothing:
```
ERROR: Failure building default configuration, disabling IOpipe.: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
```
=> Fix fatal crash for IOPIPE_ENABLED environment variable. (Fixes #131)

src/main/java/com/iopipe/IOpipeExecution.java
This deprecates the specified methods since the functions which are called will not be executed when a plugin is disabled, this is error prone and may cause different execution paths depending on the state of plugins.
=> Deprecate IOpipeExecution.plugin() methods which take functional interfaces. (Fixes #106)

PLUGINS.md, PROFILER.md, README.md
This organizes the README (and the other main documentation files).
Statistics for the README:
* Lines: 374 -> 316
* Words: 1491 -> 1450
* Characters (with spaces): 10794 -> 10563
* Characters (no spaces): 9278 -> 9139
* Bytes: 10794 -> 10563
=> Organize the README (Fixes #124)

src/main/java/com/iopipe/IOpipeExecution.java, src/main/java/com/iopipe/IOpipeMeasurement.java, src/main/java/com/iopipe/IOpipeService.java, src/main/java/com/iopipe/PerformanceEntry.java, src/main/java/com/iopipe/plugin/trace/TraceMeasurement.java, src/test/java/com/iopipe/IntegerValue.java, src/test/java/com/iopipe/__DoTracePlugin__.java
This fixes measurements being incorrect and additionally records more overhead sooner and just before the report is sent to IOpipe.
Fixes #147 and #135.
=> Record start time properly for measurements and record more overhead. (Fixes #147 and #135)

src/main/java/com/iopipe/SystemMeasurement.java
This corrects and falls back if the disk usage percent ends up being infinite or NaN.
=> Correct infinite/NaN disk usage being reported. (Fixes #154)

src/main/java/com/iopipe/plugin/trace/TraceUtils.java
This adds functional interface handlers to `TraceUtils` for measuring, it only has `Runnable` and `Supplier` since I did not want to add too many methods for doing this.
This is ready for review.
=> Add function handlers to TraceUtils. (Fixes #102)

pom.xml
If a manual deploy needs to be done for the Java agent, this will generate the needed javadoc and sources for it to be uploaded.
=> Generate sources and JavaDoc, for manual deploys. (Fixes #189)

src/main/java/com/iopipe/IOpipeService.java, src/main/java/com/iopipe/__PseudoContext__.java, src/test/java/com/iopipe/__DoTimeOut__.java
If a `Context` was not passed to the method it will use one which is derived from environment variables.
=> Use fallback `Context` if one was not specified. (Fixes #186)

src/main/java/com/iopipe/IOpipeConfiguration.java
This deprecates the static field, behavior is not changed yet.
=> Deprecate the static field for the global static config. (Fixes #171)

src/main/java/com/iopipe/__ActiveExecution__.java
If an exception is thrown when a plugin is initialized, catch the exception, log it, and then just treat the plugin as if it were disabled.
=> Do not try to reinit plugins if they throw an exception. (Fixes #182)

README.md, src/main/java/com/iopipe/IOpipeConfiguration.java, src/main/java/com/iopipe/generic/EntryPoint.java, src/test/java/com/iopipe/Engine.java, src/test/java/com/iopipe/__DoConfigFileTest__.java, src/test/resources/iopipe.properties
This will allow for using resources to set IOpipe properties which will have to be included at compile time.
=> Add resource based configuration for IOpipe. (Fixes #170, Fixes #169)

README.md
This does not directly use a version so that we do not need to make commits to update the README every time we want to do it.
=> Do not directly use a version instead refer to it. (Fixes #198)

src/test/java/com/iopipe/__WrappedConnectionFactory__.java
This removes printing the request that was sent to the server in the test code.
=> Do not print snooped requests when testing since they may contain binary data. (Fixes #203)

pom.xml
This removes the unused log4j2 from the test build.
=> Remove unused Log4j2 from test build.

pom.xml
When using JavaDoc 11 the build fails because it will assume you are trying to document Java 11 code, so this sets the source/target explicitly to Java 8 so that the build no longer fails.
=> Explicitly set source/target version so JavaDoc 11 does not assume version 11
